slideshow:
    width: 150
    height: 100

github_base: https://github.com/

githubiverse:
   generate_thumbs: false
   img_dir: shared/img/
   stl_dir: shared/stl/
   src_dir: shared/src/
   thumb_dir: thumbs/
